/**
 * Migration: create-xhs-tables
 * Version: 25.2.1
 * Generated: 2026-01-10T06:11:28.788Z
 * 
 * This migration was automatically generated by TypeORM
 * based on entity definition changes.
 */

import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1768025483356 implements MigrationInterface {
    name = 'Migration1768025483356'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "xhs_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "user_id" uuid NOT NULL, CONSTRAINT "PK_2a7c46d03d7aa525802988efb07" PRIMARY KEY ("id")); COMMENT ON COLUMN "xhs_group"."name" IS '分组名称'; COMMENT ON COLUMN "xhs_group"."is_default" IS '是否为系统默认分组'; COMMENT ON COLUMN "xhs_group"."user_id" IS '所属用户ID'`);
        await queryRunner.query(`CREATE INDEX "IDX_2a7c46d03d7aa525802988efb0" ON "xhs_group" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0a81778cb54e6d98a808b34cb" ON "xhs_group" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0a81778cb54e6d98a808b34cb" ON "xhs_group" ("user_id") `);
        await queryRunner.query(`COMMENT ON TABLE "xhs_group" IS '小红书笔记分组'`);
        await queryRunner.query(`CREATE TABLE "xhs_note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying(200) NOT NULL, "content" text NOT NULL, "cover_images" jsonb, "word_count" integer NOT NULL DEFAULT '0', "mode" character varying(50) NOT NULL DEFAULT 'ai-generate', "original_input" text, "user_id" uuid NOT NULL, "group_id" uuid, CONSTRAINT "PK_692334873c0a94122d5a39da748" PRIMARY KEY ("id")); COMMENT ON COLUMN "xhs_note"."title" IS '笔记标题'; COMMENT ON COLUMN "xhs_note"."content" IS '笔记正文内容'; COMMENT ON COLUMN "xhs_note"."cover_images" IS '封面图片URL列表'; COMMENT ON COLUMN "xhs_note"."word_count" IS '字数统计'; COMMENT ON COLUMN "xhs_note"."mode" IS '生成模式: ai-generate-AI生成, ai-compose-AI作文, add-emoji-笔记加emoji'; COMMENT ON COLUMN "xhs_note"."original_input" IS '用户原始输入内容'; COMMENT ON COLUMN "xhs_note"."user_id" IS '所属用户ID'; COMMENT ON COLUMN "xhs_note"."group_id" IS '所属分组ID'`);
        await queryRunner.query(`CREATE INDEX "IDX_692334873c0a94122d5a39da74" ON "xhs_note" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d6c0dbf7ecbca1d43b4250110" ON "xhs_note" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb1c73da800a7cf075950e2b39" ON "xhs_note" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9406500762e9ead13e1b7ad68" ON "xhs_note" ("user_id", "created_at") `);
        await queryRunner.query(`COMMENT ON TABLE "xhs_note" IS '小红书笔记'`);
        await queryRunner.query(`CREATE TABLE "xhs_hot_topic" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying(100) NOT NULL, "category" character varying(50), "usage_count" integer NOT NULL DEFAULT '0', "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f3ee17ac6a1f7c9810a71563127" PRIMARY KEY ("id")); COMMENT ON COLUMN "xhs_hot_topic"."title" IS '主题标题'; COMMENT ON COLUMN "xhs_hot_topic"."category" IS '主题分类: 美食, 美妆, 旅游, 穿搭, 好物, 萌宠, 日常等'; COMMENT ON COLUMN "xhs_hot_topic"."usage_count" IS '主题使用次数统计'; COMMENT ON COLUMN "xhs_hot_topic"."sort_order" IS '排序顺序，数值越小越靠前'; COMMENT ON COLUMN "xhs_hot_topic"."is_active" IS '是否启用该主题'`);
        await queryRunner.query(`CREATE INDEX "IDX_f3ee17ac6a1f7c9810a7156312" ON "xhs_hot_topic" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7626dc0b96f4cc27ace9ba8e1c" ON "xhs_hot_topic" ("sort_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_03b6c611565cd0e8c8720120d5" ON "xhs_hot_topic" ("usage_count") `);
        await queryRunner.query(`CREATE INDEX "IDX_633e99cc1cd0479d29cd09fc09" ON "xhs_hot_topic" ("category") `);
        await queryRunner.query(`COMMENT ON TABLE "xhs_hot_topic" IS '小红书热门主题'`);
        await queryRunner.query(`CREATE TABLE "xhs_content_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying(200) NOT NULL, "content" text NOT NULL, "category" character varying(50) NOT NULL, "usage_count" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9dd3caeecdf295c43bde0bcfe52" PRIMARY KEY ("id")); COMMENT ON COLUMN "xhs_content_template"."title" IS '模板标题'; COMMENT ON COLUMN "xhs_content_template"."content" IS '模板内容'; COMMENT ON COLUMN "xhs_content_template"."category" IS '模板分类: 美妆, OOTD, 好物分享, 探店, 美食, 萌宠, 日常等'; COMMENT ON COLUMN "xhs_content_template"."usage_count" IS '模板使用次数统计'; COMMENT ON COLUMN "xhs_content_template"."is_active" IS '是否启用该模板'`);
        await queryRunner.query(`CREATE INDEX "IDX_9dd3caeecdf295c43bde0bcfe5" ON "xhs_content_template" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1dd11d0f39d36b410e039ca8d" ON "xhs_content_template" ("usage_count") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1fbf05d8ee2883e05b4156bd6" ON "xhs_content_template" ("category") `);
        await queryRunner.query(`COMMENT ON TABLE "xhs_content_template" IS '小红书内容模板'`);
        await queryRunner.query(`CREATE TABLE "xhs_image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "url" character varying(500) NOT NULL, "type" character varying(50) NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_4f8aa3bc142213de6cf97a4a610" PRIMARY KEY ("id")); COMMENT ON COLUMN "xhs_image"."url" IS '图片URL地址'; COMMENT ON COLUMN "xhs_image"."type" IS '图片类型: auto-自动配图, template-图片模板, upload-本地上传'; COMMENT ON COLUMN "xhs_image"."user_id" IS '所属用户ID'`);
        await queryRunner.query(`CREATE INDEX "IDX_4f8aa3bc142213de6cf97a4a61" ON "xhs_image" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0f8fb23bda57934b8cc05ad6a" ON "xhs_image" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ed79b22436eb4c460a7a41d81" ON "xhs_image" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_12b943a065305cf009c0ec4779" ON "xhs_image" ("user_id", "created_at") `);
        await queryRunner.query(`COMMENT ON TABLE "xhs_image" IS '小红书图片'`);
        await queryRunner.query(`ALTER TABLE "xhs_group" ADD CONSTRAINT "FK_f0a81778cb54e6d98a808b34cb8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xhs_note" ADD CONSTRAINT "FK_8d6c0dbf7ecbca1d43b42501106" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xhs_note" ADD CONSTRAINT "FK_fb1c73da800a7cf075950e2b39d" FOREIGN KEY ("group_id") REFERENCES "xhs_group"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xhs_image" ADD CONSTRAINT "FK_c0f8fb23bda57934b8cc05ad6a7" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "xhs_image" DROP CONSTRAINT "FK_c0f8fb23bda57934b8cc05ad6a7"`);
        await queryRunner.query(`ALTER TABLE "xhs_note" DROP CONSTRAINT "FK_fb1c73da800a7cf075950e2b39d"`);
        await queryRunner.query(`ALTER TABLE "xhs_note" DROP CONSTRAINT "FK_8d6c0dbf7ecbca1d43b42501106"`);
        await queryRunner.query(`ALTER TABLE "xhs_group" DROP CONSTRAINT "FK_f0a81778cb54e6d98a808b34cb8"`);
        await queryRunner.query(`COMMENT ON TABLE "xhs_image" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12b943a065305cf009c0ec4779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ed79b22436eb4c460a7a41d81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0f8fb23bda57934b8cc05ad6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f8aa3bc142213de6cf97a4a61"`);
        await queryRunner.query(`DROP TABLE "xhs_image"`);
        await queryRunner.query(`COMMENT ON TABLE "xhs_content_template" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1fbf05d8ee2883e05b4156bd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1dd11d0f39d36b410e039ca8d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dd3caeecdf295c43bde0bcfe5"`);
        await queryRunner.query(`DROP TABLE "xhs_content_template"`);
        await queryRunner.query(`COMMENT ON TABLE "xhs_hot_topic" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_633e99cc1cd0479d29cd09fc09"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03b6c611565cd0e8c8720120d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7626dc0b96f4cc27ace9ba8e1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3ee17ac6a1f7c9810a7156312"`);
        await queryRunner.query(`DROP TABLE "xhs_hot_topic"`);
        await queryRunner.query(`COMMENT ON TABLE "xhs_note" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9406500762e9ead13e1b7ad68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb1c73da800a7cf075950e2b39"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d6c0dbf7ecbca1d43b4250110"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692334873c0a94122d5a39da74"`);
        await queryRunner.query(`DROP TABLE "xhs_note"`);
        await queryRunner.query(`COMMENT ON TABLE "xhs_group" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0a81778cb54e6d98a808b34cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0a81778cb54e6d98a808b34cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a7c46d03d7aa525802988efb0"`);
        await queryRunner.query(`DROP TABLE "xhs_group"`);
    }

}
